### ISSUE TITLE
Can't create ios project

### ISSUE THREAD

**Issue by shinriyo** [Hanks10100/weex-typescript-example#1]
I want to develop using the project.
However, it says it is not a weex project.
Why it can't?
```
$ weex platform add ios
15:42:14 : Current working directory is not a weex project.
```

**Comment by Hanks10100** [comment]
Yes, this project is not generated by `weex-toolkit`.

This is a boilerplate project for build js files from typescript source code. It's separate from native projects. You can create a standalone iOS project with Xcode.
