### ISSUE TITLE
how to access after run?

### ISSUE THREAD

**Issue by shinriyo** [Hanks10100/weex-typescript-example#2]
`npm run serve`
after.
readme said `http://localhost:12580/dist/index.min.js`
but 

<img width="1200" alt="screen shot 2018-12-08 at 8 21 39" src="https://user-images.githubusercontent.com/396927/49677482-62069c80-fac2-11e8-9db8-4dec109fb643.png">

And, it may port 8080

<img width="1200" alt="screen shot 2018-12-08 at 8 21 28" src="https://user-images.githubusercontent.com/396927/49677505-7b0f4d80-fac2-11e8-8d84-ee764dfc7c5a.png">

however, it is just file viewer...

**Comment by Hanks10100** [comment]
Put the compiled file wherever you want, make sure you can asses it via URL, and generate a QR from the URL. Then use weex playground app or your own app to scan it.
